version: "3.8"

services:
  db_base:
    image: postgres:15.4-bookworm
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  api_base:
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${API_PORT:-8030}:8000"

  client_base:
    env_file:
      - .env
    depends_on:
      - api
