name: seismic_multi

services:

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend_base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.backend
    volumes:
      - ./api/media:/var/www/seismic/api/media
    environment:
      - "ENVIRONMENT=production"
    ports:
      - "${WEBAPP_PORT:-8080}:80"
    depends_on:
      - db_psql

  client:
    extends:
      file: docker-compose.base.yml
      service: client_base
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/Dockerfile.frontend
    environment:
      - "ENVIRONMENT=production"
    ports:
      - "${CLIENT_PORT:-3030}:80"

  db_psql:
    extends:
      file: docker-compose.base.yml
      service: db_base_psql

volumes:
  seismic_psql:
