name: seismic_dev

services:

  webapp_sqlite:
    extends:
      file: docker-compose.base.yml
      service: seismic_dev_base
    volumes:
      - ./api/.db_sqlite:/var/www/seismic/api/.db_sqlite
    environment:
      - "DATABASE_ENGINE=sqlite3"
