version: "3.8"
name: seismic-dev

services:

  db:
    container_name: seismic_db-dev
    extends:
      file: dk-cp.base.yml
      service: db_base
    ports:
      - "${DB_PORT:-5444}:5432"

  api:
    container_name: seismic_api-dev
    extends:
      file: dk-cp.base.yml
      service: api_base
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/Dockerfile.backend.dev
      args:
        - ENVIRONMENT=development
    env_file:
      - .env
      - .env.dev
    environment:
      ENVIRONMENT: "development"
    volumes:
      - ./api:/var/www/seismic/api/

  client:
    container_name: seismic_client-dev
    extends:
      file: dk-cp.base.yml
      service: client_base
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/Dockerfile.frontend.dev
      args:
        - ENVIRONMENT=development
    env_file:
      - .env
      - .env.dev
    environment:
      ENVIRONMENT: "development"
    volumes:
      - ./client:/code
    ports:
      - "${CLIENT_PORT:-3030}:3000"

volumes:
    pgdata:
        name: seismic_pgdata-dev
