version: "3.8"

services:
  db:
    container_name: seismic-db
    image: postgres:15.4-bookworm
    env_file:
      - .env
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: seismic-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/code
    ports:
      - "8030:80"
    depends_on:
      - db

  client:
    container_name: seismic-client
    build:
      context: ./client
    env_file:
      - .env
    volumes:
      - ./client:/code
    ports:
      - "3030:3000"
    depends_on:
      - api

volumes:
  pgdata:
    name: seismic-risc_pgdata
