name: seismic_dev

services:

  db:
    extends:
      file: docker-compose.base.yml
      service: db_base_psql

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend_base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.backend.dev
    volumes:
      - ./api:/var/www/seismic/api
    depends_on:
      - db

  client:
    extends:
      file: docker-compose.base.yml
      service: client_base
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/Dockerfile.frontend.dev
      args:
        - ENVIRONMENT=development
    ports:
      - "${CLIENT_PORT:-3030}:3000"
    volumes:
      - ./client:/code
    depends_on:
      - backend

volumes:
  seismic_psql:
