services:

  backend_base:
    container_name: seismic_backend_dev
    env_file:
      - .env
    environment:
      - "PYTHONUNBUFFERED=1"
    restart: on-failure

  backend_dev_base:
    extends:
      service: backend_base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.backend.dev
    volumes:
      - ./api:/var/www/seismic/api
      - ./client/src:/var/www/seismic/client/src
    env_file:
      - .env
    environment:
      - "ENVIRONMENT=development"
    ports:
      - "${WEBAPP_PORT:-8080}:8000"
      - "${CLIENT_PORT:-3000}:3000"

  client_base:
    container_name: seismic_client_dev
    env_file:
      - .env
    restart: on-failure

  client_dev_base:
    container_name: client_base
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/Dockerfile.frontend.dev
      args:
        - ENVIRONMENT=development
    env_file:
      - .env
    environment:
      ENVIRONMENT: "development"
    volumes:
      - ./client:/code
    ports:
      - "${CLIENT_PORT:-3030}:3000"

  db_base:
    container_name: seismic_db_dev
    env_file:
      - .env
    restart: always

  db_base_psql:
    extends:
      service: db_base
    image: postgres:16.2
    volumes:
      - seismic_psql:/var/lib/postgresql/data
    environment:
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT:-5432}:5432"
