version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: monthly
    timezone: Europe/Bucharest
  open-pull-requests-limit: 5
  target-branch: develop
  reviewers:
  - tudoramariei
  assignees:
  - tudoramariei
  labels:
  - dependencies
  - react
