on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

name: Build Docker image

jobs:

  build:
    name: Build Docker image
    uses: code4romania/.github/.github/workflows/build-push-image.yml@main
    with:
      images: ghcr.io/code4romania/seismic-risc
      context: ./
      dockerfile: ./docker/dockerfiles/Dockerfile.backend
